# Generated by Django 4.2.25 on 2025-11-14 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0003_produtos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='data_contratacao',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='status',
        ),
        migrations.AddField(
            model_name='produtos',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produtos',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
