# Generated by Django 4.2.25 on 2025-11-15 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0005_clientes_alter_produtos_options_alter_produtos_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='em_estoque',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
