# Generated by Django 4.2.25 on 2025-11-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0006_produtos_em_estoque_alter_clientes_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinhos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=11)),
                ('cpf', models.CharField(max_length=15)),
                ('endereco', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Carrinho',
                'verbose_name_plural': 'Carrinhos',
            },
        ),
        migrations.DeleteModel(
            name='Clientes',
        ),
    ]
