# Generated by Django 4.2.25 on 2025-11-24 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0007_carrinhos_delete_clientes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Funcionarios',
        ),
    ]
