# Generated by Django 4.2.25 on 2025-11-19 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Cupom',
        ),
    ]
